### ISSUE TITLE
Componente crashes after installation

### ISSUE THREAD

**Issue by resterampeberlin** [dontinelli/fyta-custom_component#12]
## System Information

version | core-2024.1.5
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.0-rpi7-rpi-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 4. März 2024 um 19:07
-- | --
current_recorder_run | 11. März 2024 um 19:27
estimated_db_size | 10.54 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/dontinelli/fyta-custom_component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After installing the integration I get an error in the integration. The log shows:
2024-03-11 19:39:02.569 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry _[hidden for privacy]_  for fyta
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fyta/__init__.py", line 41, in async_setup_entry
    expiration: datetime | None = (datetime.fromisoformat(entry.data.get("expiration")).astimezone(ZoneInfo(tz)) if "expiration" in entry.data else None)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: fromisoformat: argument must be str

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
See above
```

**Comment by dontinelli** [comment]
Thank you @resterampeberlin for your comprehensive description of the issue. Do you have access to the config entry (config/.storage/core.config_entries) and could you paste the config entry of "expiration"?

**Comment by resterampeberlin** [comment]
It reads
"expiration": "2024-05-10T19:39:02.567950"

**Comment by dontinelli** [comment]
Does the error persist, if you restart HA? Just to be sure if it is only in the initialization after the installation or on every call of init.py.

**Comment by resterampeberlin** [comment]
Thanks for the hint. I restarted HA and now it works.

**Comment by dontinelli** [comment]
Good to hear.
I will try to find out why the error occurs only in the first initialization.

**Comment by Cambodurix** [comment]
Hi,
it seems like I have the same problem, but restarting Home Assistant doesn't work for me.
I currently only have one Fyta Beam. If I delete it in the (Android-) app, the integration starts. But as soon as I reconfigure the Beam in the app, it crashes again.

(HA Core-Version 2024.3.1)

**Comment by dontinelli** [comment]
> Hi, it seems like I have the same problem, but restarting Home Assistant doesn't work for me. I currently only have one Fyta Beam. If I delete it in the (Android-) app, the integration starts. But as soon as I reconfigure the Beam in the app, it crashes again.
> 
> (HA Core-Version 2024.3.1)

In the latest version this issue has been resolved. I assume you issue is not related to this one, as this one was not related to having a Beam or not. Please consult the logs and - if appropriate - open a separate issue also posting your logs.
