### ISSUE TITLE
Unexpected error fetching FYTA Coordinator data: 'plant'

### ISSUE THREAD

**Issue by resterampeberlin** [dontinelli/fyta-custom_component#17]
## System Information

version | core-2024.2.5
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.21-v7+
arch | armv7l
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 23. März 2024 um 11:46
-- | --
current_recorder_run | 25. März 2024 um 07:24
estimated_db_size | 14.31 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/dontinelli/fyta-custom_component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The integration crashes once in a while

### Reproduction steps

I can´t say when it happens. It just a appears in the log.

### Debug logs

```text
2024-03-25 11:42:28.976 ERROR (MainThread) [custom_components.fyta.coordinator] Unexpected error fetching FYTA Coordinator data: 'plant'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fyta/coordinator.py", line 46, in _async_update_data
    data = await self.fyta.update_all_plants()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fyta_cli/fyta_connector.py", line 73, in update_all_plants
    current_plant = await self.update_plant_data(plant)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fyta_cli/fyta_connector.py", line 85, in update_plant_data
    plant_data: dict = p["plant"]
                       ~^^^^^^^^^
KeyError: 'plant'
```

### Diagnostics dump

[home-assistant_fyta_2024-03-25T11-10-30.774Z.log](https://github.com/dontinelli/fyta-custom_component/files/14742584/home-assistant_fyta_2024-03-25T11-10-30.774Z.log)

**Comment by resterampeberlin** [comment]
As you can see from the log it happened 4h after startup. Reported values are ok. It did not happen the first time but now I am monitoring it closer.

**Comment by resterampeberlin** [comment]
Yes, that is also my impression because of the random occurrence.

**Comment by dontinelli** [comment]
@resterampeberlin: can you please confirm if issue is fixed, before I create a new release?

**Comment by resterampeberlin** [comment]
I have just pulled the update and restarted home assistant. Let´s wait and see ...

**Comment by resterampeberlin** [comment]
So far no further crashes. It seems to me that you have caught all exceptions.

**Comment by dontinelli** [comment]
> So far no further crashes. It seems to me that you have caught all exceptions.

Thank you. Just issued new release.
