### ISSUE TITLE
error during setup

### ISSUE THREAD

**Issue by stenbosch** [dontinelli/fyta-custom_component#3]
When I start the integration process, the following error message appears after the update (in the previous version, the config_flow.py ran fine.)
<img width="546" alt="Bildschirmfoto 2024-02-17 um 12 48 52" src="https://github.com/dontinelli/fyta-custom_component/assets/24548965/ee3a79d7-132d-4c9b-ae9c-8394600c7930">

In the previous version, the devices were created cleanly, but no data arrived. I also started writing an integration, but without authentication with user/password. but with bearer token. Data is already arriving there. I couldn't manage to authenticate and renew the token

**Comment by dontinelli** [comment]
Could you provide the relevant log entries?

I tested around and suddenly came across an error with the import of fyta_cli (or the fyta_client and fyta_exceptions, respectively). I had to add a leading . to fix the import.

**Comment by stenbosch** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:2275
First occurred: 15:03:14 (1 occurrences)
Last logged: 15:03:14

Error occurred loading flow for integration fyta: No module named 'fyta_connector'

**Comment by dontinelli** [comment]
This definitively looks like fyta_connector.py is not importet. Do you have the file in the custom_components/fyta folder?
If yes, try adding a leading . to the import in __init__.py, config_flow.py and coordinator.py

**Comment by wiflyerszurmontrio** [comment]
adding the dot doesn't work for me unfortunately.

**Comment by 3KniGHtcZ** [comment]
I have the same problem. Code copied in custom_components/fyta. I tried adding leading . before imports in files, but still the same status.

**Comment by dontinelli** [comment]
@JanGiese prepared a [PR](https://github.com/dontinelli/fyta-custom_component/pull/4) to push the custom component into HACS. We are currently working on this. I suggest you give us some time and you then test the updated integration.

**Comment by dontinelli** [comment]
Code has been amended. To test you can download the files from custom_components/fyta to your custom_components directory. The `fyta_cli` is now a requirement and should be downloaded automatically.
