### ISSUE TITLE
Problems after adding a new beam

### ISSUE THREAD

**Issue by Damrak2022** [dontinelli/fyta-custom_component#65]
### System Health details

Core
2024.10.1
Supervisor
2024.10.0
Operating System
13.1
Frontend
20241002.2

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/dontinelli/fyta-custom_component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After I added a new beam in the app yesterday, all plants in HA are shown as "Not available". Since I have 0.0% knowledge of programming, I can't judge what the cause is. Even restarting HA with all add-ons doesn't solve the problem. The hub has also disappeared and when I try to add it again, I am told that it is already configured.
Maybe you have an idea why this could be.
Regards Andy
<img width="315" alt="Bildschirmfoto 2024-10-11 um 14 34 52" src="https://github.com/user-attachments/assets/3960cd6f-53fa-4358-bd41-0eb083da9e33">
<img width="695" alt="Bildschirmfoto 2024-10-11 um 14 35 13" src="https://github.com/user-attachments/assets/0203a26b-bb2c-45b7-967c-0e80a1a04557">

### Reproduction steps

add a beam to the app

### Debug logs

```text
?
```

### Diagnostics dump

?

**Comment by dontinelli** [comment]
@Damrak2022 : can you confirm that you really use the custom component and not the core integration? It was my understanding that in custom component this issue has been resolved with https://github.com/dontinelli/fyta-custom_component/releases/tag/v0.1.12. In core it should be resolved with 2024.10.2.
